### ISSUE TITLE
[idea] Accelerate the skip of downloaded things

### ISSUE THREAD

**Issue by Leonardonline** [ozzieperez/packtpub-library-downloader#25]
There may be an option that if the folder already exists, it jumps directly to the next element in the array.

**Comment by ozzieperez** [comment]
Hi Joe, thanks for your feedback. I think if we jump to next element if a folder exists, you would run into an issue were you can't download a new format. For example, if you run the script once to only download pdfs, but in a second pass might want to download epubs as well, then it would just not download the epub since the folder exists.
